<?php

namespace AppBundle\Repository;

/**
 * PatronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatronRepository extends \Doctrine\ORM\EntityRepository
{
}
